version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
